//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace AppAutoSubmitBannerDFP.RefUploadFile {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="UploadSoap", Namespace="http://tempuri.org/")]
    public partial class Upload : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback SendFileOperationCompleted;
        
        private System.Threading.SendOrPostCallback SendFileV2OperationCompleted;
        
        private System.Threading.SendOrPostCallback SendFileNewOperationCompleted;
        
        private System.Threading.SendOrPostCallback SendFilePDFOperationCompleted;
        
        private System.Threading.SendOrPostCallback ApiSaveXmlAfterSendToVansOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Upload() {
            this.Url = global::AppAutoSubmitBannerDFP.Properties.Settings.Default.AppAutoSubmitBannerDFP_RefUploadFile_Upload;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event SendFileCompletedEventHandler SendFileCompleted;
        
        /// <remarks/>
        public event SendFileV2CompletedEventHandler SendFileV2Completed;
        
        /// <remarks/>
        public event SendFileNewCompletedEventHandler SendFileNewCompleted;
        
        /// <remarks/>
        public event SendFilePDFCompletedEventHandler SendFilePDFCompleted;
        
        /// <remarks/>
        public event ApiSaveXmlAfterSendToVansCompletedEventHandler ApiSaveXmlAfterSendToVansCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SendFile", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string SendFile([System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")] byte[] iData, string iPath, int MaxW, int MaxH) {
            object[] results = this.Invoke("SendFile", new object[] {
                        iData,
                        iPath,
                        MaxW,
                        MaxH});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SendFileAsync(byte[] iData, string iPath, int MaxW, int MaxH) {
            this.SendFileAsync(iData, iPath, MaxW, MaxH, null);
        }
        
        /// <remarks/>
        public void SendFileAsync(byte[] iData, string iPath, int MaxW, int MaxH, object userState) {
            if ((this.SendFileOperationCompleted == null)) {
                this.SendFileOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendFileOperationCompleted);
            }
            this.InvokeAsync("SendFile", new object[] {
                        iData,
                        iPath,
                        MaxW,
                        MaxH}, this.SendFileOperationCompleted, userState);
        }
        
        private void OnSendFileOperationCompleted(object arg) {
            if ((this.SendFileCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SendFileCompleted(this, new SendFileCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SendFileV2", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string SendFileV2([System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")] byte[] iData, string iPath, int MaxW, int MaxH) {
            object[] results = this.Invoke("SendFileV2", new object[] {
                        iData,
                        iPath,
                        MaxW,
                        MaxH});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SendFileV2Async(byte[] iData, string iPath, int MaxW, int MaxH) {
            this.SendFileV2Async(iData, iPath, MaxW, MaxH, null);
        }
        
        /// <remarks/>
        public void SendFileV2Async(byte[] iData, string iPath, int MaxW, int MaxH, object userState) {
            if ((this.SendFileV2OperationCompleted == null)) {
                this.SendFileV2OperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendFileV2OperationCompleted);
            }
            this.InvokeAsync("SendFileV2", new object[] {
                        iData,
                        iPath,
                        MaxW,
                        MaxH}, this.SendFileV2OperationCompleted, userState);
        }
        
        private void OnSendFileV2OperationCompleted(object arg) {
            if ((this.SendFileV2Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SendFileV2Completed(this, new SendFileV2CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SendFileNew", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string SendFileNew([System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")] byte[] iData, string iPath, int MaxW, int MaxH) {
            object[] results = this.Invoke("SendFileNew", new object[] {
                        iData,
                        iPath,
                        MaxW,
                        MaxH});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SendFileNewAsync(byte[] iData, string iPath, int MaxW, int MaxH) {
            this.SendFileNewAsync(iData, iPath, MaxW, MaxH, null);
        }
        
        /// <remarks/>
        public void SendFileNewAsync(byte[] iData, string iPath, int MaxW, int MaxH, object userState) {
            if ((this.SendFileNewOperationCompleted == null)) {
                this.SendFileNewOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendFileNewOperationCompleted);
            }
            this.InvokeAsync("SendFileNew", new object[] {
                        iData,
                        iPath,
                        MaxW,
                        MaxH}, this.SendFileNewOperationCompleted, userState);
        }
        
        private void OnSendFileNewOperationCompleted(object arg) {
            if ((this.SendFileNewCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SendFileNewCompleted(this, new SendFileNewCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SendFilePDF", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string SendFilePDF([System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")] byte[] f, string fileName) {
            object[] results = this.Invoke("SendFilePDF", new object[] {
                        f,
                        fileName});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SendFilePDFAsync(byte[] f, string fileName) {
            this.SendFilePDFAsync(f, fileName, null);
        }
        
        /// <remarks/>
        public void SendFilePDFAsync(byte[] f, string fileName, object userState) {
            if ((this.SendFilePDFOperationCompleted == null)) {
                this.SendFilePDFOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendFilePDFOperationCompleted);
            }
            this.InvokeAsync("SendFilePDF", new object[] {
                        f,
                        fileName}, this.SendFilePDFOperationCompleted, userState);
        }
        
        private void OnSendFilePDFOperationCompleted(object arg) {
            if ((this.SendFilePDFCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SendFilePDFCompleted(this, new SendFilePDFCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ApiSaveXmlAfterSendToVans", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int ApiSaveXmlAfterSendToVans(string sXml, string sFileName) {
            object[] results = this.Invoke("ApiSaveXmlAfterSendToVans", new object[] {
                        sXml,
                        sFileName});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void ApiSaveXmlAfterSendToVansAsync(string sXml, string sFileName) {
            this.ApiSaveXmlAfterSendToVansAsync(sXml, sFileName, null);
        }
        
        /// <remarks/>
        public void ApiSaveXmlAfterSendToVansAsync(string sXml, string sFileName, object userState) {
            if ((this.ApiSaveXmlAfterSendToVansOperationCompleted == null)) {
                this.ApiSaveXmlAfterSendToVansOperationCompleted = new System.Threading.SendOrPostCallback(this.OnApiSaveXmlAfterSendToVansOperationCompleted);
            }
            this.InvokeAsync("ApiSaveXmlAfterSendToVans", new object[] {
                        sXml,
                        sFileName}, this.ApiSaveXmlAfterSendToVansOperationCompleted, userState);
        }
        
        private void OnApiSaveXmlAfterSendToVansOperationCompleted(object arg) {
            if ((this.ApiSaveXmlAfterSendToVansCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ApiSaveXmlAfterSendToVansCompleted(this, new ApiSaveXmlAfterSendToVansCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void SendFileCompletedEventHandler(object sender, SendFileCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SendFileCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SendFileCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void SendFileV2CompletedEventHandler(object sender, SendFileV2CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SendFileV2CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SendFileV2CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void SendFileNewCompletedEventHandler(object sender, SendFileNewCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SendFileNewCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SendFileNewCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void SendFilePDFCompletedEventHandler(object sender, SendFilePDFCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SendFilePDFCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SendFilePDFCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void ApiSaveXmlAfterSendToVansCompletedEventHandler(object sender, ApiSaveXmlAfterSendToVansCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ApiSaveXmlAfterSendToVansCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ApiSaveXmlAfterSendToVansCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591